[package]
name = "seedrs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
anyhow = { workspace = true }
colored = { workspace = true }
which = "6.0"
rayon = "1.10"
derive_builder = "0.20.0"
degit = { path = "../degit" }
