[package]
name = "degit"
version = "0.1.0"
edition = "2021"

[lib]
name = "degit"
path = "src/lib.rs"

[[bin]]
name = "degit"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
anyhow = { workspace = true }
regex = "1.10"
colored = "2.1"
